"""init: booking table

Revision ID: 591d1ac34eae
Revises: bd177e735916
Create Date: 2025-04-08 22:44:11.061309

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "591d1ac34eae"
down_revision: Union[str, None] = "bd177e735916"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "booking",
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("date_start", sa.Date(), nullable=False),
        sa.Column("date_end", sa.Date(), nullable=False),
        sa.Column("hotel_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["hotel_id"], ["hotel.hotel_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("booking_id"),
    )
    op.create_index(op.f("ix_booking_hotel_id"), "booking", ["hotel_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_booking_hotel_id"), table_name="booking")
    op.drop_table("booking")
    # ### end Alembic commands ###
