services:
  db:
    container_name: "db"
    image: postgres:15.1
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - local

  backend:
    container_name: "backend"
    build:
      context: .
      dockerfile: config/Dockerfile
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      bash -c "
      while !</dev/tcp/db/5432; do
        echo 'Waiting for database...';
        sleep 1;
      done;
    networks:
      - local

networks:
  local:
    driver: bridge
